language: dart
sudo: required
dist: trusty
dart:
  - stable
  - dev
before_script:
  - dart run tekartik_travis_ci_flutter:install
  - source $(dart run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
