language: dart
os:
  - osx
dart:
  - 3.3.0
before_install:
  - brew update
install:
  - brew install dart
  - pub get
branches:
  only:
    - main
coveralls: true
notifications:
  email: false
dart_task:
  - test: --platform chrome
