os: osx
language: dart

dart:
  - stable

before_install:
  - brew update
  - brew install --HEAD usbmuxd
  - brew link usbmuxd
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - brew install cocoapods || true
  - pod repo update

install:
  - gem install cocoapods -v '1.10.2'
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - brew install cocoapods || true
  - pod repo update
  - flutter pub get

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool
    - $HOME/Library/Caches/Homebrew

script:
  - flutter test
  - flutter build ios
