language: dart
os:
  - osx
dart:
  - 3.3.0
install:
  - brew install --cask flutter
  - pub get
  - flutter pub get
  - flutter doctor
  - flutter pub run build_runner build --delete-conflicting-outputs
script:
  - dart --version
branches:
  only:
    - main
coveralls: true
notifications:
  email: false
